### ISSUE TITLE
Pixelated results

### ISSUE THREAD

**Issue by yk1711** [nwtn/php-respimg#1]
Hi,

Thanks for this library, saved us time researching optimal imagemagick-based settings. However, we're using your class and getting very lossy results on our images (using smartresize without optimizations). Could you take a look and tell what's wrong ? We don't really resize the image, but pass original image dimensions, we just use imagemagick to make sure we get normalized results when editors upload big images to our CMS.

[Smartresized](https://s3-eu-west-1.amazonaws.com/vf-emporio/article_images/129/section_images/14388992260297.jpeg)

[Original](https://s3-eu-west-1.amazonaws.com/vf-emporio/article_images/24/section_images/14376540126916.jpeg)

**Comment by EFSpooner** [comment]
Hello!

You could try setting to another filter (see http://old.dylanbeattie.net/magick/filters/result.html for comparisons) in the Respimg.php file.

I think lanczos looks and works best.
`$this->thumbnailImage($columns, $rows, false, false, \Imagick::FILTER_LANCZOS);`

**Comment by nwtn** [comment]
Closing because this repo is not maintained
