### ISSUE TITLE
I resized an image, but the image is blurry

### ISSUE THREAD

**Issue by krasho** [nwtn/php-respimg#2]
Hello Dave.

I used your pluggin in one image (1200 x 1500). I want to resize it to 400 x 500 px, but the images is blurry,

I am sending original image
![2](https://cloud.githubusercontent.com/assets/10523191/12839998/ba9e9d68-cb93-11e5-9170-56c2d0d6da36.jpg)

I used the following code:

  $image2 = new nwtn\Respimg($tempImage);
  $image2->smartResize(400, 500, false);
  $image2->writeImage($fullImage);

2_plugin is the image resized with plugin.
![2_plugin](https://cloud.githubusercontent.com/assets/10523191/12840125/20615bda-cb95-11e5-8b27-7e67f2812b34.jpg)

2new2 is a resized image with this command:
convert 2.jpg -resize "400x" -unsharp 2x0.5+0.7+0 -quality 100 2new2.jpg
![2new2](https://cloud.githubusercontent.com/assets/10523191/12840132/3688ab48-cb95-11e5-96f1-53578901602a.jpg)

2new2 is more sharp .

**Comment by krasho** [comment]
I used:
- MAC OS X - Yosemite
- PHP 5.6
- MAMP PRO 3.4

**Comment by nwtn** [comment]
this is expected behaviour. although the default settings work great for _most_ use cases, it looks like they may not be appropriate in yours. sorry.

**Comment by krasho** [comment]
Hello David. Thanks for your time, why could the reason? Is my image wrong?
Do you have any suggest for me?

Thanks

**Comment by nwtn** [comment]
I don't think there's anything wrong with the image, it's just that some of the choices I made that help reduce the file size can sometimes result in blurriness like this. You might be better off using [PHP’s Imagick](http://php.net/manual/en/book.imagick.php) and modifying [the options I’m using](https://github.com/nwtn/php-respimg/blob/master/src/Respimg.php#L237-L255) to get something that works better for you.

**Comment by krasho** [comment]
Thanks David.
