### ISSUE TITLE
smartResize is causing General error: 1205 Lock wait timeout exceeded issue

### ISSUE THREAD

**Issue by wakqasahmed** [nwtn/php-respimg#3]
I found the project really promising and testing revealed nice results. But in production the following code is causing multiple issues.

```
$image = new nwtn\Respimg($input_filename);
$image->smartResize($output_width, 0, true);
$image->writeImage($output_filename);
nwtn\Respimg::optimize($output_filename, 0, 1, 0, 0);
```
Second line, i.e. smartResize is often causing `SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction` in my symfony application.

I know it is because my session table is causing trouble but it is due to the processing time of smartResize (exceeding to more than a minute for resolutions like 1000x1000 or even smaller)

Any clue how to reduce this time, I am using Ubuntu 14.04 4GB RAM (never found a high usage on new relic so the server is enough strong it seems).

**Comment by nwtn** [comment]
Closing because this repo is not maintained
