### ISSUE TITLE
Respimg::optimize is taking quite longer

### ISSUE THREAD

**Issue by wakqasahmed** [nwtn/php-respimg#4]
I found the project really promising and testing revealed nice results. But in production the following code is causing multiple issues.

```
$image = new nwtn\Respimg($input_filename);
//$image->smartResize($output_width, 0, true);
$image->writeImage($output_filename);
nwtn\Respimg::optimize($output_filename, 0, 1, 0, 0);
```
To test, I commented smartResize line and found out that PNG images are still taking quite a lot of time.

Fourth line, i.e. Respimg::optimize is now causing trouble in my symfony application.

<img width="985" alt="screen shot 2017-04-11 at 9 53 12 am" src="https://cloud.githubusercontent.com/assets/4486133/24894640/c4b4502e-1e9c-11e7-899f-3e9ec23a6554.png">
<img width="983" alt="screen shot 2017-04-11 at 9 51 26 am" src="https://cloud.githubusercontent.com/assets/4486133/24894639/c4b4119a-1e9c-11e7-9dbb-05367348a999.png">

Any clue how to reduce this time, I am using Ubuntu 14.04 4GB RAM (never found a high usage on new relic so the server is enough strong it seems).

**Comment by yellow1912** [comment]
I don't think you should ever run optimization during a request, perhaps via cli is a better solution? Image optimization is too resource intensive and can easily cause timeout.

**Comment by nwtn** [comment]
Closing because this repo is not maintained
