### ISSUE TITLE
Undefined class constant 'ALPHACHANNEL_OPAQUE'

### ISSUE THREAD

**Issue by 44db** [nwtn/php-respimg#5]
I've upgraded
from -> ImageMagick 6.9.4.3 Q16 x86_64
to -> ImageMagick 7.0.5-0 Q16 x86_64

and I get this error: Undefined class constant 'ALPHACHANNEL_OPAQUE'

Does it have to do with the library? Is it something else?
Could you help/guide me to the right direction?

Thanks

**Comment by Whissi** [comment]
Same problem after I upgraded ImageMagick from v6.x to v7.x.

From https://pecl.php.net/package-changelog.php?package=imagick (3.4.3RC1):
> * Several ALPHACHANNEL_* constants are only available in ImageMagick < 7
IMAGICK_REGISTER_CONST_LONG("ALPHACHANNEL_RESET", ResetAlphaChannel);
IMAGICK_REGISTER_CONST_LONG("ALPHACHANNEL_COPY", CopyAlphaChannel);
IMAGICK_REGISTER_CONST_LONG("ALPHACHANNEL_OPAQUE", OpaqueAlphaChannel);
> * Several ALPHACHANNEL_* constants are only available in ImageMagick >= 7. These constants re-use the values of the constants removed.
IMAGICK_REGISTER_CONST_LONG("ALPHACHANNEL_ON", OnAlphaChannel);
IMAGICK_REGISTER_CONST_LONG("ALPHACHANNEL_OFF", OffAlphaChannel);
IMAGICK_REGISTER_CONST_LONG("ALPHACHANNEL_DISCRETE", DiscreteAlphaChannel);

I am not an ImageMagick expert. However, when you read [imagick's source code](https://github.com/mkoppanen/imagick/blob/ddb1fa81b520f29b1d13c00ea17d2522c8c154bc/imagick_helpers.c#L1703), it looks like `ALPHACHANNEL_OFF` replaces `ALPHACHANNEL_OPAQUE`:
```C
#if MagickLibVersion >= 0x700
        IMAGICK_REGISTER_CONST_LONG("ALPHACHANNEL_OFF", OffAlphaChannel);
#else
        IMAGICK_REGISTER_CONST_LONG("ALPHACHANNEL_OPAQUE", OpaqueAlphaChannel);
#endif
```
...so my fix looks like
```DIFF
@@ -182,7 +182,12 @@ class Respimg extends Imagick {

                // if the alpha channel is not defined, make it opaque
                if ( $this->getImageAlphaChannel() == Imagick::ALPHACHANNEL_UNDEFINED ) {
-                       $this->setImageAlphaChannel( Imagick::ALPHACHANNEL_OPAQUE );
+                       if ( defined( 'Imagick::ALPHACHANNEL_OFF' ) ) {
+                               $this->setImageAlphaChannel( Imagick::ALPHACHANNEL_OFF );
+                       }
+                       elseif ( defined( 'Imagick::ALPHACHANNEL_OPAQUE' ) ) {
+                               $this->setImageAlphaChannel( Imagick::ALPHACHANNEL_OPAQUE );
+                       }
                }
```

**Comment by nwtn** [comment]
Closing because this repo is not maintained
