### ISSUE TITLE
Uncaught exception 'ImagickException' with message 'The image profile does not exist'

### ISSUE THREAD

**Issue by jarred-cz** [nwtn/php-respimg#6]
Hi there,

most of time the library works perfectly, but with some JPG it ends with following error:

**PHP Fatal error**:  Uncaught exception '**ImagickException**' with message '**The image profile does not exist**' in /.../vendor/nwtn/php-respimg/src/**Respimg.php:386**

BTW many thanks (mainly for php-respimg itself!).

**Comment by jarred-cz** [comment]
Possible fix:

**Respimg.php**

`385: try {`
`386:  $this->removeImageProfile($key);`
`387: } catch (\ImagickException $e) {`
`388:  ...`
`389: }`

**Comment by nwtn** [comment]
Closing because this repo is not maintained
